### ISSUE TITLE
AddFieldNames should use a service?

### ISSUE THREAD

**Issue by azaroth42** [thegetty/pipeline#32]
... to benefit from the auto-service code?

Then when we need access to the names, it gets them in the same way as it gets any other configured data, and just drop them into the directory with all the other setup datasets.

**Comment by azaroth42** [comment]
For your emmy consideration: https://github.com/thegetty/pipeline/blob/knoedler_update/pipeline/nodes/basic.py#L157-L166

**Comment by kasei** [comment]
I think this is a good pattern, but wonder if there's a way to make it more broadly useful. For example, in the PIR pipeline, I have three different header files that I pull from, so this pattern:

```python
field_names = Service('header_names')
```

Wouldn't work, as the service name is hard-coded.

**Comment by azaroth42** [comment]
Yeah, in knoedler I use keys to pick which of the lists to use which avoids that issue.

Not sure as to the internals of how the service is actually built out, I just followed the bonobo docs for referencing services. Perhaps it could be instantiated in __init__ with the service name passed to it?

**Comment by kasei** [comment]
Maybe. Let's move ahead with this, and we can look into making it useful for the sales use case as we go.

**Comment by kasei** [comment]
For CSV data, headers were implemented not as services but as sidecar CSV files. This has the same benefits of a service (decoupling the code from the data) while keeping the data and metadata in the same place.
