### ISSUE TITLE
Access to project specific data from pipeline.linkedart

### ISSUE THREAD

**Issue by azaroth42** [thegetty/pipeline#33]
pipeline.linkedart generates (for example) people in make_la_person, but has a fallback to UUIDs.

Shouldn't it either error, or have access to conventions for building the tag ... eg concatenating `UID_TAG_PREFIX` and `data['uid']`?

**Comment by kasei** [comment]
We can improve it, yes. My thinking for UUID fallbacks was that I have several places where there simply is no identifying information, and so UUIDs seem just fine.

Not everything *needs* to use the tag URIs, but we might choose to use them anyway for the sake of consistency.

**Comment by kasei** [comment]
This was resolved by refactoring the code into `pipeline.projects.PersonIdentity.make_person` and its project-specific subclasses.
