### ISSUE TITLE
Merged HumanMadeObjects contain redundant dimensions, material statements

### ISSUE THREAD

**Issue by kasei** [thegetty/pipeline#55]
When two objects are merged as a result of being identified as the same object that took part in a prev/post sale, some data is not identified as redundant and so ends up being asserted multiple times in the resulting JSON-LD. For example, [this painting data](https://github.com/thegetty/pipeline/files/3672389/jupiter.json.txt) has two dimension statements that assert the same data, but in different ways (one just in `pouces`, the other in `pieds` and `pouces`). No extra semantic information is added to the `Dimension` value here (though there may be some value in keeping the multiple `Dimension Statements`).

Similarly, this object has two `Material Statements`, with identical content (`"sur toile"`). This would be an easier pattern to identify and merge, but it will not happen automatically, as the `referred_to_by` property *can* accept multiple values and these `LinguisticObject` values do not have an `id` and do not base their identity on their `content` (cf. `Name` and `Identifier` for which we have explicitly asserted that their identity is based on their `content` values).

I suspect having redundant data like this will be problematic for the UI development, but am not sure how to proceed. For the material statements, I can improve the merging code to identify specific types of `LinguisticObject`s (dimension and material Statements) that are content-based, but the former case of lexically differing but semantically identical dimension statements is more challenging. Thoughts?

**Comment by kasei** [comment]
I'm not sure about the correctness/appropriateness of this, but one approach would be to assign URIs to the `MaterialStatement`s, `DimensionStatement`s, and `Dimension`s that would be merged along with their `HumanMadeObject`s. If different records make different claims about the materials or dimensions of an object, we might end up with strange/incorrect data, but I'm not sure if that would be a problem in practice.

**Comment by azaroth42** [comment]
If there are two statements of the same type, with exactly the same content, then that's definitely good to merge them.  Ditto for dimensions (same value, unit and type).

If there's any difference, then we should keep them.  We should confirm about non identical content, e.g. whether the GRI cares about case or punctuation.

**Comment by kasei** [comment]
Differences in case/punctuation would definitely be a challenge for material statements.

For dimensions, case/punctuation won't matter because the value merging is based on is the parsed and normalized form. So two different dimension statements turn into a single dimension with multiple `Name`s:

```json
{
  "type": "Dimension",
  "value": "61.0",
  "classified_as": [
	{
	  "id": "http://vocab.getty.edu/aat/300055647",
	  "type": "Type",
	  "_label": "Width"
	}
  ],
  "identified_by": [
	{
	  "type": "Name",
	  "content": "61 French inches"
	},
	{
	  "type": "Name",
	  "content": "5 French feet, 1 French inch"
	}
  ],
  "unit": {
	"id": "http://vocab.getty.edu/aat/300435502",
	"type": "MeasurementUnit",
	"_label": "Paris inches"
  }
}
```

Currently, even those names are the result of some processing, so they are *not* the original text from the input files. They are the normalized lexical versions that result from parsing (e.g. `'`, `feet`, `foot`, and `ft` all become `feet` or `foot` (depending on cardinality), and the values are normalized as floating point values (`1/4` becomes `0.25`). This last point might deserve some discussion, as fractions that produce non-terminating decimals are a bit unsightly.
